from reportlab.lib.pagesizes import LETTER
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib import colors
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, PageBreak, Table, TableStyle
from io import BytesIO
from datetime import datetime
from typing import Dict, Any, Optional
import logging

logger = logging.getLogger(__name__)

# Internationalization Dictionary
I18N = {
    "es": {
        "report_title": "Informe de Teoría Fundamentada",
        "project": "Proyecto",
        "date": "Fecha de Generación",
        "central_category": "Categoría Central",
        "paradigm_model": "Modelo Paradigmático (Strauss)",
        "propositions": "Proposiciones Teóricas",
        "gap_analysis": "Análisis de Saturación y Brechas",
        "confidence": "Índice de Confianza",
        "generated_by": "Generado por",
        "version": "Versión",
        "no_data": "Sin datos disponibles",
        "conditions": "Condiciones",
        "actions": "Acciones/Interacciones",
        "consequences": "Consecuencias",
        "gaps_found": "Brechas Identificadas",
    },
    "en": {
        "report_title": "Grounded Theory Report",
        "project": "Project",
        "date": "Generation Date",
        "central_category": "Central Category",
        "paradigm_model": "Paradigmatic Model (Strauss)",
        "propositions": "Theoretical Propositions",
        "gap_analysis": "Saturation & Gap Analysis",
        "confidence": "Confidence Score",
        "generated_by": "Generated by",
        "version": "Version",
        "no_data": "No data available",
        "conditions": "Conditions",
        "actions": "Actions/Interactions",
        "consequences": "Consequences",
        "gaps_found": "Identified Gaps",
    }
}

class ExportService:
    def __init__(self):
        self.styles = getSampleStyleSheet()
        self._setup_custom_styles()

    def _setup_custom_styles(self):
        # Custom styles for TheoGen brand
        self.styles.add(ParagraphStyle(
            name='TheoGenTitle',
            parent=self.styles['Heading1'],
            fontSize=24,
            textColor=colors.indigo,
            spaceAfter=30,
            alignment=1 # Center
        ))
        self.styles.add(ParagraphStyle(
            name='TheoGenSection',
            parent=self.styles['Heading2'],
            fontSize=18,
            textColor=colors.indigo,
            spaceBefore=20,
            spaceAfter=12,
            borderPadding=5,
            borderWidth=0,
            leftIndent=0
        ))
        self.styles.add(ParagraphStyle(
            name='TheoGenBody',
            parent=self.styles['Normal'],
            fontSize=11,
            leading=14,
            spaceAfter=10
        ))

    async def generate_theory_pdf(
        self, 
        project_name: str, 
        language: str, 
        theory_data: Dict[str, Any]
    ) -> BytesIO:
        """Generates a professional PDF report from theory data."""
        
        buffer = BytesIO()
        doc = SimpleDocTemplate(buffer, pagesize=LETTER, rightMargin=72, leftMargin=72, topMargin=72, bottomMargin=72)
        
        lang = language if language in I18N else "es"
        texts = I18N[lang]
        
        elements = []
        
        # 1. Title & Header
        elements.append(Paragraph(texts["report_title"], self.styles['TheoGenTitle']))
        
        header_data = [
            [texts["project"], project_name],
            [texts["date"], datetime.now().strftime("%Y-%m-%d %H:%M")],
            [texts["version"], str(theory_data.get("version", 1))],
            [texts["confidence"], f"{theory_data.get('confidence_score', 0) * 100:.1f}%"],
            [texts["generated_by"], theory_data.get("generated_by", "TheoGen AI")]
        ]
        
        header_table = Table(header_data, colWidths=[150, 300])
        header_table.setStyle(TableStyle([
            ('TEXTCOLOR', (0, 0), (0, -1), colors.grey),
            ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 10),
            ('GRID', (0, 0), (-1, -1), 0.5, colors.lightgrey),
            ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ]))
        elements.append(header_table)
        elements.append(Spacer(1, 40))
        
        # 2. Central Category
        elements.append(Paragraph(texts["central_category"], self.styles['TheoGenSection']))
        model_json = theory_data.get("model_json", {})
        central_cat = model_json.get("selected_central_category", texts["no_data"])
        elements.append(Paragraph(f"<b>{central_cat}</b>", self.styles['TheoGenBody']))
        
        # 3. Paradigmatic Model
        elements.append(Paragraph(texts["paradigm_model"], self.styles['TheoGenSection']))
        
        paradigm_data = [
            [texts["conditions"], model_json.get("conditions", texts["no_data"])],
            [texts["actions"], model_json.get("actions", texts["no_data"])],
            [texts["consequences"], model_json.get("consequences", texts["no_data"])]
        ]
        
        p_table = Table(paradigm_data, colWidths=[120, 330])
        p_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (0, -1), colors.whitesmoke),
            ('INNERGRID', (0, 0), (-1, -1), 0.25, colors.grey),
            ('BOX', (0, 0), (-1, -1), 0.25, colors.grey),
            ('VALIGN', (0, 0), (-1, -1), 'TOP'),
            ('PADDING', (0, 0), (-1, -1), 8),
        ]))
        elements.append(p_table)
        elements.append(Spacer(1, 20))
        
        # 4. Propositions
        elements.append(PageBreak())
        elements.append(Paragraph(texts["propositions"], self.styles['TheoGenSection']))
        propositions = theory_data.get("propositions", [])
        if not propositions:
            elements.append(Paragraph(texts["no_data"], self.styles['TheoGenBody']))
        else:
            for i, prop in enumerate(propositions, 1):
                # Handle both string and dict propositions
                text = prop if isinstance(prop, str) else prop.get("text", texts["no_data"])
                elements.append(Paragraph(f"{i}. {text}", self.styles['TheoGenBody']))
        
        # 5. Gap Analysis
        elements.append(Spacer(1, 20))
        elements.append(Paragraph(texts["gap_analysis"], self.styles['TheoGenSection']))
        gaps = theory_data.get("gaps", [])
        if not gaps:
            elements.append(Paragraph(texts["no_data"], self.styles['TheoGenBody']))
        else:
            elements.append(Paragraph(texts["gaps_found"] + ":", self.styles['Normal']))
            for gap in gaps:
                text = gap if isinstance(gap, str) else gap.get("description", texts["no_data"])
                elements.append(Paragraph(f"• {text}", self.styles['TheoGenBody']))

        # Build PDF
        doc.build(elements)
        buffer.seek(0)
        return buffer

export_service = ExportService()
